-- Run this SQL in your Supabase SQL Editor to create the journal_posts table
CREATE TABLE public.journal_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  category TEXT NOT NULL,
  content TEXT,
  image_url TEXT,
  slug TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.journal_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public.journal_posts FOR SELECT
USING (true);

CREATE POLICY "Enable full access for authenticated users"
ON public.journal_posts FOR ALL
USING (auth.role() = 'authenticated')
WITH CHECK (auth.role() = 'authenticated');
