-- Drops the old bookings table that used snake_case and replaces it with the schema expected by the frontend
drop table if exists public.bookings;

create table public.bookings (
  id bigint generated by default as identity primary key,
  ref text not null,
  guest text not null,
  email text not null,
  phone text not null,
  country text,
  requests text,
  room text not null,
  "roomSlug" text not null,
  "roomType" text not null,
  "checkIn" text not null,
  "checkOut" text not null,
  guests integer not null,
  nights integer not null,
  extras jsonb,
  subtotal numeric not null,
  tax numeric not null,
  total numeric not null,
  "paymentMethod" text not null,
  status text not null,
  source text not null,
  created_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

create policy "Allow public insert" on public.bookings for insert with check (true);
create policy "Allow public select" on public.bookings for select using (true);
create policy "Allow public update" on public.bookings for update using (true);
create policy "Allow public delete" on public.bookings for delete using (true);

-- Reload schema cache to instantly reflect changes
NOTIFY pgrst, reload_schema;
