-- Run this SQL in your Supabase SQL Editor to create the offers table
CREATE TABLE public.offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag TEXT NOT NULL,
  title TEXT NOT NULL,
  price TEXT NOT NULL,
  from_label TEXT NOT NULL DEFAULT 'from',
  perks JSONB NOT NULL DEFAULT '[]',
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: `perks` expects an array of strings natively coerced via Postgrest to string[]
-- Set up open RLS policies (Optional but recommended for public reading)
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public.offers FOR SELECT
USING (true);

-- Allow authenticated/service role admin inserts
CREATE POLICY "Enable full access for authenticated users" 
ON public.offers FOR ALL 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');
