supabase db query --file supabase_contacts_migration.sqlcreate table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  "firstName" text not null,
  "lastName" text not null,
  email text not null,
  phone text,
  "enquiry_type" text not null,
  message text not null,
  status text not null default 'unread',
  created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;

create policy "Allow public insert" on public.contacts for insert with check (true);
create policy "Allow public select" on public.contacts for select using (true);
create policy "Allow update" on public.contacts for update using (true);

-- Reload schema cache to instantly reflect changes
NOTIFY pgrst, reload_schema;
