create table if not exists public.gallery_images (
  id bigint generated by default as identity primary key,
  src text not null,
  alt text not null,
  tag text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.gallery_images enable row level security;

create policy "Allow public read-only access."
  on public.gallery_images for select
  using ( true );

create policy "Allow authenticated insert."
  on public.gallery_images for insert
  to authenticated
  with check ( true );

create policy "Allow authenticated update."
  on public.gallery_images for update
  to authenticated
  using ( true );

create policy "Allow authenticated delete."
  on public.gallery_images for delete
  to authenticated
  using ( true );

-- Reload schema cache in case table was added but not recognized
NOTIFY pgrst, reload_schema;
