/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiningRouteImport } from './routes/dining'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminGuestsRouteImport } from './routes/admin.guests'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as ApiBookingsSendConfirmationRouteImport } from './routes/api.bookings.send-confirmation'
import { Route as ApiStaffInviteRouteImport } from './routes/api.staff.invite'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiningRoute = DiningRouteImport.update({
  id: '/dining',
  path: '/dining',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const ApiBookingsSendConfirmationRoute =
  ApiBookingsSendConfirmationRouteImport.update({
    id: '/api/bookings/send-confirmation',
    path: '/api/bookings/send-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStaffInviteRoute = ApiStaffInviteRouteImport.update({
  id: '/api/staff/invite',
  path: '/api/staff/invite',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/bookings/send-confirmation': typeof ApiBookingsSendConfirmationRoute
  '/api/staff/invite': typeof ApiStaffInviteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin': typeof AdminIndexRoute
  '/api/bookings/send-confirmation': typeof ApiBookingsSendConfirmationRoute
  '/api/staff/invite': typeof ApiStaffInviteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/dining': typeof DiningRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/offers': typeof OffersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rooms': typeof RoomsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/bookings/send-confirmation': typeof ApiBookingsSendConfirmationRoute
  '/api/staff/invite': typeof ApiStaffInviteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/dining'
    | '/events'
    | '/gallery'
    | '/offers'
    | '/reset-password'
    | '/rooms'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/contacts'
    | '/admin/gallery'
    | '/admin/guests'
    | '/admin/logs'
    | '/admin/offers'
    | '/admin/rooms'
    | '/admin/'
    | '/api/bookings/send-confirmation'
    | '/api/staff/invite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/dining'
    | '/events'
    | '/gallery'
    | '/offers'
    | '/reset-password'
    | '/rooms'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/contacts'
    | '/admin/gallery'
    | '/admin/guests'
    | '/admin/logs'
    | '/admin/offers'
    | '/admin/rooms'
    | '/admin'
    | '/api/bookings/send-confirmation'
    | '/api/staff/invite'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/book'
    | '/contact'
    | '/dining'
    | '/events'
    | '/gallery'
    | '/offers'
    | '/reset-password'
    | '/rooms'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/contacts'
    | '/admin/gallery'
    | '/admin/guests'
    | '/admin/logs'
    | '/admin/offers'
    | '/admin/rooms'
    | '/admin/'
    | '/api/bookings/send-confirmation'
    | '/api/staff/invite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DiningRoute: typeof DiningRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  OffersRoute: typeof OffersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomsRoute: typeof RoomsRoute
  ApiBookingsSendConfirmationRoute: typeof ApiBookingsSendConfirmationRoute
  ApiStaffInviteRoute: typeof ApiStaffInviteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dining': {
      id: '/dining'
      path: '/dining'
      fullPath: '/dining'
      preLoaderRoute: typeof DiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guests': {
      id: '/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/bookings/send-confirmation': {
      id: '/api/bookings/send-confirmation'
      path: '/api/bookings/send-confirmation'
      fullPath: '/api/bookings/send-confirmation'
      preLoaderRoute: typeof ApiBookingsSendConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/staff/invite': {
      id: '/api/staff/invite'
      path: '/api/staff/invite'
      fullPath: '/api/staff/invite'
      preLoaderRoute: typeof ApiStaffInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminGuestsRoute: AdminGuestsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DiningRoute: DiningRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  OffersRoute: OffersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomsRoute: RoomsRoute,
  ApiBookingsSendConfirmationRoute: ApiBookingsSendConfirmationRoute,
  ApiStaffInviteRoute: ApiStaffInviteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
