-- Activity logs for tracking staff changes
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_email text not null,
  user_role text not null,
  action text not null,
  resource_type text not null,
  resource_id text,
  resource_name text,
  details jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for efficient querying
create index if not exists idx_activity_logs_created_at on public.activity_logs(created_at desc);
create index if not exists idx_activity_logs_user_email on public.activity_logs(user_email);
create index if not exists idx_activity_logs_action on public.activity_logs(action);

alter table public.activity_logs enable row level security;

-- Everyone authenticated can read their own and global logs
create policy "Public reads logs" on public.activity_logs for select using (true);

-- Only staff can insert logs (via server functions)
create policy "Staff insert logs" on public.activity_logs for insert to authenticated
  with check (true);

notify pgrst, 'reload schema';
