-- Run this migration in the Supabase SQL editor (or with the Supabase CLI).
-- It replaces the missing `rooms` relation that currently returns HTTP 404.
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  number text not null unique,
  name text,
  slug text unique,
  type text not null,
  view text not null default 'Garden View',
  capacity integer not null default 2 check (capacity > 0),
  price numeric not null check (price >= 0),
  status text not null default 'available' check (status in ('available', 'occupied', 'cleaning', 'maintenance')),
  floor integer not null default 1,
  description text,
  image_url text,
  amenities text[] not null default '{}',
  beds text,
  size_sqm integer,
  popular boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.rooms enable row level security;

create policy "Anyone can view available room types" on public.rooms for select using (true);
create policy "Authenticated users manage rooms" on public.rooms for all to authenticated using (true) with check (true);

-- Create bookings table for hotel reservations
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  guest_name text not null,
  guest_email text not null,
  guest_phone text,
  check_in date not null,
  check_out date not null,
  number_of_guests integer not null default 1 check (number_of_guests > 0),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'checked_in', 'checked_out', 'cancelled')),
  total_price numeric not null check (total_price >= 0),
  special_requests text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.bookings enable row level security;

-- The existing booking flow needs authenticated admins to update a reservation.
create policy "Authenticated users manage bookings" on public.bookings for all to authenticated using (true) with check (true);
